better capture

diff --git a/run-license-verify/action.yml b/run-license-verify/action.yml
--- a/run-license-verify/action.yml
+++ b/run-license-verify/action.yml
@@ -13,15 +13,17 @@ runs:
       id: check_verify
       shell: bash
       run: |
-        $GITHUB_ACTION_PATH/../script/licenses --verify || result=$?
+        output=$($GITHUB_ACTION_PATH/../script/licenses --verify || 1)
+        result=$?
 
         if [ $result -eq 0 ] ; then
           echo "All licenses are up to date!"
         else
-          $GITHUB_ACTION_PATH/../script/licenses --update
+          $GITHUB_ACTION_PATH/../script/licenses --update || 1
+          result=$?
 
           if git diff-index --quiet HEAD --; then
-            echo "There was an error generating files locally! Try running script/licenses --verify locally to see what's wrong."
+            echo "There was an error generating files! Try running script/licenses --verify locally to see what's wrong."
             exit 1
           else
             echo "Licenses updated successfully!"
