lean into the bash

diff --git a/run-license-verify/action.yml b/run-license-verify/action.yml
--- a/run-license-verify/action.yml
+++ b/run-license-verify/action.yml
@@ -13,19 +13,19 @@ runs:
       id: check_verify
       shell: bash
       run: |
-        $GITHUB_ACTION_PATH/../script/licenses --verify
+        $GITHUB_ACTION_PATH/../script/licenses --verify || result=$?
 
-    - name: Run license update
-      if: failure() # If the verify step fails, run the update step
-      shell: bash
-      run: |
-        $GITHUB_ACTION_PATH/../script/licenses --update
-
-        if git diff-index --quiet HEAD --; then
-          echo "There was an error generating files locally! Try running script/licenses --verify locally to see what's wrong."
-          exit 1
+        if [ $result -eq 0 ] ; then
+          echo "All licenses are up to date!"
         else
-          echo "Licenses updated successfully!"
+          $GITHUB_ACTION_PATH/../script/licenses --update
+
+          if git diff-index --quiet HEAD --; then
+            echo "There was an error generating files locally! Try running script/licenses --verify locally to see what's wrong."
+            exit 1
+          else
+            echo "Licenses updated successfully!"
+          fi
         fi
 
     - name: Commit licenses
