Prepare for the non-inclusion of systests

diff --git a/.github/workflows/rails_test_suite.yml b/.github/workflows/rails_test_suite.yml
--- a/.github/workflows/rails_test_suite.yml
+++ b/.github/workflows/rails_test_suite.yml
@@ -10,11 +10,15 @@ on:
       postgres_username:
         required: false
         type: string
-        default: ""
+        default: "app"
       postgres_database_name:
         required: false
         type: string
-        default: ""
+        default: "app_test"
+      with_system_tests:
+        required: false
+        type: boolean
+        default: true
 
 permissions:
   contents: write
@@ -86,20 +90,22 @@ jobs:
       - uses: yettoapp/actions/setup-languages@main
         with:
           ruby: true
-          node: true
+          node: ${{ inputs.with_system_tests == true }}
 
       - name: Set up the database
         shell: bash
         run: |
-          bundle exec rails db:create db:schema:load
+          bundle exec rails db:create db:schema:load || echo 'DB could not be created!'
 
-      - name: Get Vite cache restore key
+      - if: ${{ inputs.with_system_tests == true }}
+        name: Get Vite cache restore key
         id: restored-vite-cache-key
         shell: bash
         run: |
           echo "digest=$(bin/rails r 'print ViteRuby.digest')" >> $GITHUB_OUTPUT
 
-      - name: Cache assets
+      - if: ${{ inputs.with_system_tests == true }}
+        name: Cache assets
         id: cache-assets
         uses: actions/cache/restore@v4
         with:
@@ -111,7 +117,8 @@ jobs:
             asset-cache-${{ runner.os }}-
             asset-cache-
 
-      - name: Precompile assets
+      - if: ${{ inputs.with_system_tests == true }}
+        name: Precompile assets
         shell: bash
         run: |
           bin/rails assets:precompile
@@ -121,14 +128,14 @@ jobs:
         with:
           github_token: ${{ secrets.gh_token }}
 
-      - if: ${{ always() }}
+      - if: ${{ always() && inputs.with_system_tests == true }}
         name: Get Vite save restore key
         id: new-vite-cache-key
         shell: bash
         run: |
             echo "digest=$(bin/rails r 'print ViteRuby.digest')" >> $GITHUB_OUTPUT
 
-      - if: ${{ always() && steps.new-vite-cache-key.outputs.digest != steps.restored-vite-cache-key.outputs.digest }}
+      - if: ${{ always() && inputs.with_system_tests == true && steps.new-vite-cache-key.outputs.digest != steps.restored-vite-cache-key.outputs.digest }}
         name: Cache Vite assets
         uses: actions/cache/save@v4
         with:
@@ -137,8 +144,8 @@ jobs:
             tmp/cache/vite
           key: asset-cache-${{ runner.os }}-${{ steps.new-vite-cache-key.outputs.digest }}
 
-      - uses: actions/upload-artifact@v3
-        if: ${{ always() && steps.run-tests.outcome == 'failure' }}
+      - uses: actions/upload-artifact@v4
+        if: ${{ always() && inputs.with_system_tests == true && steps.run-tests.outcome == 'failure' }}
         with:
           name: capybara_failure_screenshots
           path: ./tmp/capybara
